default: export execute

EVAL := "typst eval --root=../.. --input callisto-export=true --in test.typ"

SPLIT := '''
import json
for nb in json.load(open(0, encoding="utf-8")):
    name = nb["metadata"]["callisto"]["export-name"]
    with open(f"export-{name}.ipynb", "w", encoding="utf-8") as f:
        json.dump(nb, f)
'''

EXEC := '''
import subprocess, glob
args = ["jupyter-nbconvert", "--to", "notebook", "--execute", "--inplace"]
for file in glob.glob("export-*.ipynb"):
    subprocess.run(args + [file], check=True)
'''

export:
    @echo "Exporting notebooks..."
    @{{EVAL}} 'query(<notebook>).map(x => x.value)' | python3 -c '{{SPLIT}}'   

execute:
    @echo "Executing notebooks..."
    @python3 -c '{{EXEC}}'

watch:
    watchexec -w . -f '**/*.typ' just export execute
