default: export execute

EVAL := "typst eval --root=../.. --input callisto-export=true --in test.typ"
EXEC := "jupyter-nbconvert --to notebook --execute --inplace"
    
export-individually:
    {{EVAL}} 'query(<python>).first().value' > export-python.ipynb
    {{EVAL}} 'query(<sympy>).first().value'  > export-sympy.ipynb
    {{EVAL}} 'query(<julia>).first().value'  > export-julia.ipynb

export:
    #!/usr/bin/env bash
    {{EVAL}} 'query(<notebook>).map(x => x.value)' |
        jq -c '.[]' | while read -r nb; do
            filename=$(jq -r '.metadata.callisto."export-name"' <<<"$nb")
            echo "$nb" > "export-${filename}.ipynb"
        done

execute:
    for file in export-*.ipynb; do {{EXEC}} "$file"; done

watch:
    watchexec -w . -f '**/*.typ' just export execute
