default: export execute
    
export:
    typst eval --root=../.. --input callisto-export=true --in test.typ 'query(<notebook>).first().value' > export.ipynb
    typst eval --root=../.. --input callisto-export=true --in test.typ 'query(<sympy>).first().value'    > export-sympy.ipynb
    typst eval --root=../.. --input callisto-export=true --in test.typ 'query(<julia>).first().value'    > export-julia.ipynb

execute:
    jupyter-nbconvert --to notebook --execute --inplace export.ipynb
    jupyter-nbconvert --to notebook --execute --inplace export-sympy.ipynb
    jupyter-nbconvert --to notebook --execute --inplace export-julia.ipynb

watch:
    watchexec -w . -f '**/*.typ' just export execute
    
